"""Access to committed, labelled sample data in data/sample/ (generated by data/scripts/generate_sample_data.py)."""

import json
from datetime import datetime
from functools import lru_cache
from typing import Any

from app.canonical.models import Provenance
from app.config import SAMPLE_DIR


@lru_cache
def load_sample(rel_path: str) -> dict[str, Any]:
    return json.loads((SAMPLE_DIR / rel_path).read_text())


def sample_provenance(meta: dict[str, Any], note: str | None = None) -> Provenance:
    return Provenance(
        source=meta["source"],
        reference_timestamp=datetime.fromisoformat(meta["reference_timestamp"]) if meta.get("reference_timestamp") else None,
        dataset_version=meta.get("dataset_version"),
        geographic_scope=meta.get("geographic_scope"),
        is_sample=bool(meta.get("is_sample", True)),
        is_synthetic=bool(meta.get("is_synthetic", True)),
        mode="demo",
        note=note or meta.get("note") or None,
    )
